### ISSUE TITLE
Back Swipe Gesture Is Not Working Always

### ISSUE THREAD

**Issue by nidhinp** [Abedalkareem/LanguageManger-iOS#5]
First of all, thanks for this amazing Repo.

There is an issue with default UINavigation back gesture (the gesture to go back to previous screen). It's not always working. I found the issue in your example project also.

**Comment by Abedalkareem** [comment]
Hello nidhinp,

Thank you for using it, I saw the issue and I tried to fix it without any luck.
maybe in the future, I'll find the way to fix this.

You can try this solution 
https://stackoverflow.com/questions/47525211/change-interactivepopgesturerecognizer-direction

Thank you.
