### ISSUE TITLE
How to load storyboard localization after change language

### ISSUE THREAD

**Issue by lecong** [Abedalkareem/LanguageManger-iOS#6]
Thanks for source code.

But, I do not reload screen after change language. I using storyboard localization.

Please help me fix it.

**Comment by Abedalkareem** [comment]
Hello Lecong,
sorry, I have done this to support the localization string file, not storyboards.

But can you share more details about the issue?

Thank you.

**Comment by Abedalkareem** [comment]
Hi lecong,

Now I added support for the storyboard localization.

Thank you !!

**Comment by lecong** [comment]
How to use it? 
I reload root view controller it not working
`UIApplication.topViewController!.dismiss(animated: true) {
            let delegate = UIApplication.shared.delegate as! AppDelegate
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            delegate.window?.rootViewController = storyboard.instantiateInitialViewController()
}`
